apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-httpd
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webserver
  template:
    metadata:
      labels:
        app: webserver
    spec:
      containers:
        - name: cntr-httpd
          image: httpd:2.4.38
          ports:
            - containerPort: 80
          command: ["/bin/bash", "-c"]
          args:
            - |
              echo "You've hit - $HOSTNAME" > /usr/local/apache2/htdocs/index.html
              httpd-foreground

